on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    tags:
      - deploy
       
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ${{ secrets.LOCAL_PATH }}
          remote_path: ${{ secrets.REMOTE_PATH}}
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
              
